--CREATE TABLE ttmatrices.o2pnr (origin VARCHAR, destination varchar, deptime smallint, traveltime integer);
--COPY ttmatrices.o2pnr from '/Users/kristincarlson/Dropbox/Bus-Highway/Task3/Restart2/IntermodalAccess/1_TTMatrixLink/Auto_O_PNR_TT_Calc-results.csv' delimiter ',' csv header;
--select count(*) from ttmatrices.o2pnr;